# Generated by Django 5.2.1 on 2025-06-03 22:28

from django.db import migrations

def populate_status(apps, schema_editor):
    entries = {
        "published": "The post is published and visible to all.",
        "draft": "The post is a draft and not yet published.",
        "archived": "The post is archived and no longer active.",
    }
    Status = apps.get_model('posts', 'Status')
    for key, value in entries.items():
        status_obj = Status(name=key, description=value)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_status_post_created_on_post_status'),
    ]

    operations = [
        migrations.RunPython(populate_status),
    ]
